name: Deploy CI
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14.19.3'

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: 2

      - name: Node version
        run: node -v

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build:static

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
