name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    defaults:
      run:
        working-directory: bot

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Logging into GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_TOKEN }}
          
      - name: Print current directory
        run: ls -la

      - name: Pushing Image to Github Container Registry
        uses: docker/build-push-action@v2
        with:
          context: .
          version: latest
          push: true
          tags: ghcr.io/gendesign_course:latest

      - name: Deploy to Docker Host
        uses: appleboy/ssh-action@master
        with:
          host: 84.201.158.229
          username: adam
          key: ${{ secrets.DOCKER_SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Stop all running Docker Containers
            docker kill $(docker ps -q)

            # Free up space
            docker system prune -a

            # Login to Github Container Registry
            docker login https://ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GH_TOKEN }}

            # Pull the Docker Image 
            docker pull ghcr.io/${{ github.repository }}:latest

            # Run a new container from a new image
            docker run -d -p 80:8080 -p 443:443 -t ghcr.io/gendesign_course:latest

